DROP TABLE IF EXISTS TEST;

CREATE TABLE VENDEDOR (CODIGO LONG PRIMARY KEY, NOME VARCHAR(255), CATEGORIA INT);
CREATE TABLE PRODUTO(CODIGO LONG PRIMARY KEY, NOME VARCHAR(80), PRECO DECIMAL, DATA_INICIO_VIGENCIA DATE);
CREATE TABLE VENDA(CODIGO LONG PRIMARY KEY AUTO_INCREMENT, DATA_VENDA DATE, QUANTIDADE INT, COD_VENDEDOR LONG, COD_PRODUTO 
LONG, FOREIGN KEY (COD_VENDEDOR) REFERENCES VENDEDOR(CODIGO), FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(CODIGO));
