/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.edu.unirio.pm.display;

import br.edu.unirio.pm.model.Vendedor;
import br.edu.unirio.pm.service.MesEscolhido;
import br.edu.unirio.pm.service.ServicosComissoes;
import br.edu.unirio.pm.service.ServicosVendas;
import br.edu.unirio.pm.service.ServicosVendedores;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Felipe
 */
public class TelaTotaisVendasComissoesPorMes extends javax.swing.JInternalFrame {
    
    private ServicosVendas servicosVendas;
    private ServicosComissoes servicosComissoes;
    private ServicosVendedores servicosVendedores;
    private DefaultTableModel modeloTabela;
    private double totalVendaMensal;
    private double totalComissaoMensal;

    /**
     * Creates new form TelaTotaisVendasComissoesPorMes
     */
    public TelaTotaisVendasComissoesPorMes() {
        servicosVendas = new ServicosVendas();
        servicosComissoes = new ServicosComissoes();
        servicosVendedores = new ServicosVendedores();
        initComponents();
        preencherMeses();
        preencherAnos();
        iniciarTabela();
    }
    
    private void preencherMeses(){
        for (int mes = 1; mes<=12; mes++)
            selecioneMes.addItem(mes);
    }
    
    private void preencherAnos(){
        try {
            List<Integer> listaAnosDisponiveisParaConsulta = servicosVendas.obterAnosDisponiveisParaConsulta();
            for (int ano : listaAnosDisponiveisParaConsulta)
                selecioneAno.addItem(ano);
        } catch (SQLException ex) {
            exibirMensagemDialogo("Ocorreu o seguinte erro: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        selecioneAno = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        selecioneMes = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTotaisVendasComissoesPorMes = new javax.swing.JTable();
        botaoOk = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Totais de Vendas e Comissões por Vendedor / Mês");
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel1.setText("Ano");

        jLabel2.setText("Mês");

        tabelaTotaisVendasComissoesPorMes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome do Vendedor", "Total de Vendas", "Total de Comissões"
            }
        ));
        jScrollPane1.setViewportView(tabelaTotaisVendasComissoesPorMes);

        botaoOk.setText("OK");
        botaoOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selecioneAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selecioneMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoOk)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(selecioneAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(selecioneMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoOk))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOkActionPerformed

        MesEscolhido mesEscolhido = verificarMesEscolhido();
        iniciarTabela();
        try {
            List<Vendedor> listaVendedores = servicosVendedores.obterListaVendedores();
            for (Vendedor vendedor : listaVendedores){
                inserirDadosDoVendedorNaTabela(vendedor, mesEscolhido);
            }
        } catch (SQLException ex) {
            exibirMensagemDialogo(ex.getMessage());
        }
        servicosComissoes = new ServicosComissoes();
    }//GEN-LAST:event_botaoOkActionPerformed

    private void iniciarTabela(){
        String[][] dadosTabela = {};
        String[] cabecalhoTabela = {"Nome do Vendedor", "Total de Vendas", "Total de Comissões"};
        modeloTabela = new DefaultTableModel(dadosTabela, cabecalhoTabela);
        tabelaTotaisVendasComissoesPorMes.setModel(modeloTabela);
    }
    
    private void inserirDadosDoVendedorNaTabela(Vendedor vendedor, MesEscolhido mesEscolhido) throws SQLException{
        String nomeVendedor = vendedor.getNome();
        totalVendaMensal = servicosComissoes.obterTotalVendaMensalPorVendedor(vendedor, mesEscolhido);
        totalComissaoMensal = servicosComissoes.obterComissaoMensalPorVendedor(vendedor, mesEscolhido);
        Object dados[] = {nomeVendedor, NumberFormat.getCurrencyInstance().format(totalVendaMensal), NumberFormat.getCurrencyInstance().format(totalComissaoMensal)};
        modeloTabela.addRow(dados);
    }
    
    private MesEscolhido verificarMesEscolhido(){
        int ano = (int)selecioneAno.getSelectedItem();
        int mes = (int)selecioneMes.getSelectedItem();
        MesEscolhido mesEscolhido = new MesEscolhido(ano, mes);
        return mesEscolhido;
    }
    
    private void exibirMensagemDialogo(String textoMensagem){
        JOptionPane.showMessageDialog(null, textoMensagem);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox selecioneAno;
    private javax.swing.JComboBox selecioneMes;
    private javax.swing.JTable tabelaTotaisVendasComissoesPorMes;
    // End of variables declaration//GEN-END:variables
}
